services:
  - type: web
    name: saki-images
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1